commit
vukasin-bulatovic-ey/mars-project pull request #1
Opened 2021-06-25 09:09 UTC by vukasin-bulatovic-ey

2021-06-28 17:44 UTC, mitrovic-jovana commented on src/Carosel/Carosel.js
>      const {data}=useFetch(`https://api.nasa.gov/planetary/apod?api_key=${key}&count=${count}`)
Don't invoke service inside Carousel component. That way carousel is not customizable. It will only work with data returned from NASA api. The point of customizable carousel is to work with all kind of data we pass to it.
Instead, you should invoke service in the parent component (Home page) and pass the response to the carousel.

Also, don't hardcode urls and api keys in components. Define them like constants and store them in separate file. That way you can reuse them in other components in the future. Investigate what are the best practices for storing api keys inside React applications

2021-06-28 17:46 UTC, mitrovic-jovana commented on src/Carosel/Carosel.js
> + const r= () =>{setWidth(window.innerWidth)}
Defined variables should have meaningful name, so when someone reads your code can see right away what is the purpose of that variable. 'r' is not meaningful

2021-06-28 17:47 UTC, mitrovic-jovana commented on src/Carosel/Carosel.js
>          const [podatak,setPodatak]=useState(null)
Use only English, please

2021-06-28 17:47 UTC, mitrovic-jovana commented on src/Carosel/Carosel.js
> +}            {podatak && podatak.map(el => <Picture info={el}></Picture>).slice(start,end)}
If your component doesn’t have any children, then use self-closing tags. It improves readability.

2021-06-28 17:51 UTC, mitrovic-jovana commented on src/Carosel/Carosel.js
> +{     start !==0 && <button  onClick={()=>leftArrowFunction()}  className='arrow-left'><i className="fas fa-arrow-left"></i></button>
Don't use anonymous functions in jsx if not needed. You don't pass any parameters to leftArrorFunction so you can write just onClick={leftArrowFunction}

<i> can be self closing tab

2021-06-28 17:52 UTC, mitrovic-jovana commented on src/Carosel/Carosel.js
> +            <span className={"ringSpan " + (start === 0 ? 'background' : '')}></span>
Use ES6 template strings
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

2021-06-28 17:53 UTC, mitrovic-jovana commented on src/Picture/Picture.js
> +        <div className='picture'>
You destructure info object. It would be much cleaner

2021-06-28 18:19 UTC, mitrovic-jovana commented on src/Carosel/Carosel.js
> +               setEnd(end +4)
Don't hardcode number of cards in the carousel. Pass it as props

2021-06-28 18:24 UTC, mitrovic-jovana requested changes
Hi Vukasin, please see my comments below and update PR accordingly:

- Code formatting is not good, missing spaces, not indented… I would suggest you use extensions for formatting (ESLint or Prittier) and change settings in VS code to auto format on save. There is no need to manually format everything. Properly formatted code is a must
- Use only English in your code
- Rename Carosel component to Carousel
- It’s not good practice to add components directly to src folder. Organize your folder structure better, e.g. you can have these folders:  components, pages, assets, services etc.
- You have unique key warning in the console. This needs to be fixed
- There is a warning in the console for duplicate props in the Footer component
- Description inside carousel card is overlapping
- Add pointer cursor for buttons and ey logo for better UX
- Variables and functions need to have meaningful name (For example inside Header component you have handle() function. That name does not indicate what’s the responsibility of the function)
- Responsive design needs more work

My biggest concerns are formatting, folder structure, function and variable naming, mobile design

2021-06-29 13:34 UTC, vukasin-bulatovic-ey commented
samo da javim odradio sam one promene

2021-06-29 16:02 UTC, mitrovic-jovana commented on src/Components/Carousel/Carousel.js
> +    } else if (width <= 768 && width > 360) {
Just change here width < 375. That's way on some mobile devices I see two cards one below the other

2021-06-29 16:02 UTC, mitrovic-jovana commented on src/Components/Carousel/Carousel.js
> +      } else if (width <= 768 && width > 360) {
Here too

2021-06-29 16:02 UTC, mitrovic-jovana approved these changes
Good job Vukasin! Code looks way more cleaner now 👍 I am merging it

2021-06-29 16:03 UTC, merged